import filter from 'lodash.filter'
const currency = [
  {
    code: 'nad',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'npr',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'pkr',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'pln',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'pyg',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 4,
  },
  {
    code: 'rsd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'srd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'std',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 4,
  },
  {
    code: 'syp',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'szl',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'afn',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'tnd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'tzs',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'uah',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'bdt',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'bgn',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'bnd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'btn',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'bwp',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'byn',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'bzd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'cdf',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'clp',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 4,
  },
  {
    code: 'cop',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'ars',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'bbd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'bhd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'sek',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'bsd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'bmd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'mxn',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'bob',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'brl',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'cad',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'crc',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'gel',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'idr',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 4,
  },
  {
    code: 'inr',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'irr',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 5,
  },
  {
    code: 'jod',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'kwd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'kzt',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'mop',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'nio',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'qar',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'ron',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'rub',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'sgd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'zmw',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'aed',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'tmt',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'aoa',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'try',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'awg',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'kes',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'lbp',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'mzn',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'ngn',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'xpf',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'nzd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'omr',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'pab',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'sdg',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'php',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'sar',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'dkk',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'dop',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'dzd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'egp',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'fjd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'ghs',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'gtq',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'hrk',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'huf',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'ils',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'jmd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'khr',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'kpw',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'lak',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 4,
  },
  {
    code: 'lkr',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'lrd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'mad',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'mkd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'mmk',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'mur',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'ugx',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 4,
  },
  {
    code: 'pen',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'uzs',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'nok',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'cup',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'czk',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 1,
  },
  {
    code: 'all',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'amd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'azn',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'bam',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'thb',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'twd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'uyu',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 2,
  },
  {
    code: 'xaf',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
  {
    code: 'xcd',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 2,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 0,
  },
  {
    code: 'xof',
    currencyType: 'F',
    decimalPlace: 8,
    displayDecimalPlace: 0,
    displayUnitDecimalPlace: 0,
    firstCurrencyRatePlace: 3,
  },
]

export default function getDisabledCurrencyConfig (_code) {
  return filter(currency, { code: _code })
}
